theme: jekyll-theme-cayman
title: Roels Blog
description: Journey through my adventures while developing software.
permalink: /:title:output_ext
collections:
  article_tags:
    output: true
    permalink: /tag/:slug/